	new juicebox({
		containerId: 'juicebox-container',
		themeUrl: 'css/theme.css',
		galleryHeight:"100%",
		containerId:"juicebox-container",
				galleryHeight: "90%",
				gallerywidth: "90%",
				showSplashPage: "never",
				firstImageIndex:"1",
				showAutoPlayButton:"true",
				showInfoButton:"false",
				showNavButtons:"false",
				showBackButton:"false",
				galleryTitlePosition:"NONE",
				backButtonPosition: "NONE",
				showThumbPagingText: "true",
				maxThumbColumns: "8",
				enableDirectLinks: "false",
				captionPosition: "BELOW_IMAGE",
				backButtonUseIcon: "false",
				autohideThumbs: "false",
				buttonBarPosition: "top",
				showThumbsOnLoad:"true",
				thumbFrameWidth:"0",
				showExpandGalleryButton: "false",
				showOpenButton: "false",
				showExpandButton:"false",
				showThumbsButton: "false",
				backgroundColor: "#000000",
				buttonBarHAlign: "left",
				randomiseImages:"false",
				screenMode:"auto",
				showImageNav:"NEVER",
				showSmallThumbsOnLoad: "true",
				showSmallThumbsButton: "false",
				showSmallThumbNav: "true",
				showSmallPagingText: "false",
				showImageNumber:"false",
				imageScaleMode: "scale_down",
				maxCaptionHeight: "50",
				thumbWidth:"75",
				thumbHeight:"60",
				autohideThumbs:"false",
				inactivityTimeout:"5",
				frameWidth:"1",
				imageFrameColor: "#808080",
				thumbFrameWidth:"1",
				thumbHoverFrameWidth:"1",
				thumbSelectedFrameWidth:"4",
				thumbShadowBlur:"0",
				thumbFrameColor: "#808080",
				galleryFontFace: "Work Sans",
				topAreaHeight:"50",
				buttonBarIconSize:"20",
				imageVAlign:"top"
	});